# Use an official lightweight Python image
FROM python:3.14-slim
# Set working directory inside the container
WORKDIR /code

COPY ./app ./app

RUN pip install --no-cache-dir -r app/requirements.txt
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8090"]