# Use an official lightweight Python image
FROM python:3.14-slim
# Set working directory inside the container
WORKDIR /app

COPY ./main.py .
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8090"]